version: "3.5"

services:

  ddp-vault:
    image: vault:1.13.3
    container_name: ${DDP_VAULT_NAME}
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      DDP_DRIVER_CLASS: "org.postgresql.Driver"
      DDP_DB_URL: jdbc:postgresql://${DDP_PG_METADB_NAME}:5432/${DDP_META_DB}
      DDP_DB_USER: ${DDP_META_DB_USERNAME}
      DDP_DB_PASS: ${DDP_META_DB_PASS}
    entrypoint: /bin/sh /v/init/vault-server.sh
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - ./vault/init:/v/init
      - ./vault/vol/keys:/v/keys
      - ./vault/vol/logs:/v/logs
    restart: always
    networks:
      - ddp-network

  ddp-openldap:
    image: osixia/openldap:1.5.0
    container_name: ${DDP_LDAP_NAME}
    environment:
      LDAP_DOMAIN: "ddp.com"
      LDAP_BASE_DN: "dc=ddp,dc=com"
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASS}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASS}
      LDAP_TLS: "false"
    command: /init/add_users.sh
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap/init:/init
    restart: always
    networks:
      - ddp-network

  ddp-phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: ${DDP_PHP_LDAP_NAME}
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${DDP_LDAP_NAME}
      PHPLDAPADMIN_HTTPS: false
    depends_on:
      - ddp-openldap
    ports:
      - "8001:80"
    restart: always
    networks:
      - ddp-network

networks:
  ddp-network:
    name: ddp-ext-network
    driver: bridge
